### ISSUE TITLE
missing src.rock

### ISSUE THREAD

**Issue by fperrad** [aiq/basexx#6]
Currently, on luarocks.org, you upload the rockspec, could you add too the src.rock ?

**Comment by aiq** [comment]
Yeah, I can do it in a few days. But why is the rockspec not enough?

**Comment by fperrad** [comment]
I work on [Buildroot](https://buildroot.org/) a embedded linux distribution.
Basically, the system must be built off-line (after fetching all sources), so, with a Lua package, a rockspec alone is not enough, the src.rock is needed.

**Comment by aiq** [comment]
I added a .src.rock file for the version 0.4.0.
I hope everything worgs now as it should be.
