### ISSUE TITLE
Providing src.rock for every release

### ISSUE THREAD

**Issue by jocelynthode** [aiq/basexx#9]
Hey,

I'm currently trying to install jitsi-meet-tokens on an offline installation and unfortunately the latest basexx 0.4.1 does not come with an .src.rock which forced me to use the 0.4.0 as someone requested a .src.rock for this.

Could you please add one for 0.4.1 as well?

Let me know if I can help you with this in any way

**Comment by aiq** [comment]
Hi,

you can find the src.rock for 0.4.1 at https://luarocks.org/manifests/aiq/basexx-0.4.0-1.src.rock

I hope this solves your problem.

**Comment by jocelynthode** [comment]
Hey thanks for the quick fix :). In the meantime I had packed it manually from the repo and used it to do a local install. But this will make it easier for my future installs of jitsi!
